apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: service-bay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
        - name: jobmanager
          image: flink:1.20-java17
          args: ["jobmanager"]
          envFrom:
            - configMapRef:
                name: flink-config
          ports:
            - containerPort: 6123
              name: rpc
            - containerPort: 6124
              name: blob
            - containerPort: 8081
              name: webui
            - containerPort: 9249
              name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: service-bay
spec:
  type: NodePort
  selector:
    app: flink
    component: jobmanager
  ports:
    - name: rpc
      port: 6123
      targetPort: 6123
    - name: blob
      port: 6124
      targetPort: 6124
    - name: webui
      port: 8081
      targetPort: 8081
      nodePort: 30082
    - name: metrics
      port: 9249
      targetPort: 9249
