global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: customer-service
    metrics_path: /metrics
    static_configs:
      - targets: ["customer-service:8080"]

  - job_name: vehicle-service
    metrics_path: /metrics
    static_configs:
      - targets: ["vehicle-service:8081"]

  - job_name: flink
    static_configs:
      - targets: ["flink-jobmanager:9249", "flink-taskmanager:9249"]
