apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: service-bay
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: customer_db
  DB_SSLMODE: disable
  API_PORT: "8080"
  KAFKA_BROKERS: kafka:9092
  KAFKA_PRODUCER_TOPIC: customer.events
  KAFKA_CONSUMER_TOPIC: identity.user-events
  KAFKA_CONSUMER_GROUP: customer-service
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: service-bay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: customer-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: customer-service-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: service-bay
spec:
  type: NodePort
  selector:
    app: customer-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
